apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: evcc
      defaultBucket: evcc
    secureJsonData:
      token: $todo_influx_token
    isDefault: true