{
 "title": "Energy Management",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Aktuelle KPI (Key Performance Indicator - Kennwerte)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "PV-Leistung",
   "type": "stat",
   "description": "Aktuelle Leistung der PV Anlage",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"pvPower\")\n  |> keep(columns: [\"_field\", \"source\", \"_value\"])\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Netzbezug / Netzeinspeisung",
   "type": "stat",
   "description": "positiv - Laden vom Netz  \nnegativ - Einspeisen ins Netz",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"gridPower\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Ladeleistung Batterie",
   "type": "stat",
   "description": "positiv - Batterie entlädt  \nnegativ - Batterie läd",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"batteryPower\")\n  |> keep(columns: [\"_field\", \"source\", \"_value\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Ladeleistung Tesla",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"chargePower\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Ladezustand Batterie % (SOC)",
   "type": "gauge",
   "description": "SOC - State Of Charge",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"batterySoc\")\n  |> keep(columns: [\"_field\", \"source\", \"_value\"])\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Pv-Leistung + Hausverbrauch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"pvPower\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.id == \"1\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  "
    },
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"homePower\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"chargePower\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"batteryPower\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> filter(fn: (r) => r.id == \"1\")\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0 }))\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Ladezustand Tesla % (SOC)",
   "type": "gauge",
   "description": "SOC - State Of Charge",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r._measurement == \"vehicleSoc\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> last()\n"
    }
   ]
  },
  { "title": "Nice to know", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Autarkie",
   "type": "timeseries",
   "description": "Autarkie Zu Hause / Wallbox",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -7d) // Zeitraum: letzte 7 Tage\n  |> filter(fn: (r) =>\n    (r._measurement == \"greenShareHome\")\n    and r._field == \"value\"\n  )\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -7d) // Zeitraum: letzte 7 Tage\n  |> filter(fn: (r) =>\n    (r._measurement == \"greenShareLoadpoints\")\n    and r._field == \"value\"\n  )\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "from(bucket: \"evcc\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gridPower\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r._value > 0)\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}